config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :letters
end

app/models/client.rb
class Client < ActiveRecord::Base
	has_and_belongs_to_many :letter

end

app/models/letter.rb
class Letter < ActiveRecord::Base
  has_and_belongs_to_many :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	
	def index
    		@clients = Client.all
	end

	def show
		@client = Client.find params[:id]
	end

	def new
    	@client = Client.new
  	end

  	def create
  		@client = Client.new client_params
  		if @client.save

  			 # Tell the UserMailer to send a welcome email after save
        	MyMailer.welcome_email(@client).deliver
  			
  			redirect_to clients_path
  		else
  			render :action => :new
  		end

  	end

	def edit
		@client = Client.find params[:id]
	end

	def update
		@client = Client.find params[:id]
		if @client.update_attributes client_params
			redirect_to client_path
		else
			render :action => :edit
		end
	end

	def destroy
    	@client = Client.find params[:id]
    	@client.destroy
    	redirect_to clients_path
  	end

	private

	def client_params
		params.require(:client).permit(:imie, :nazwisko, :email)
	end 

end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
	
	def index
		@letters  = Letter.all
	end

	def show
		@letter = Letter.find params[:id]
	end

	def new
    	@letter = Letter.new
  	end

  	def create
  		@letter = Letter.new letter_params

  		if @letter.save
  			 # Tell the MessageMailerr to send a Message email after save
        	@clients = Client.all

        	@clients.each do |client|
        		MessageMailer.send_message(client, @letter).deliver
        	end

  			redirect_to letters_path
  		else
  			render :action => :new
  		end

  	end

	def edit
		@letter = Letter.find params[:id]
	end

	def update
		@letter = Letter.find params[:id]
		if @letter.update_attributes letter_params
			redirect_to letter_path
		else
			render :action => :edit
		end
	end

	def destroy
    	@letter = Letter.find params[:id]
    	@letter.destroy
    	redirect_to letters_path
  	end

	private

	def letter_params
		params.require(:letter).permit(:title, :topic, :content)
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<%= form_for @client do |form| %>
	<%= form.text_field :imie %> </br>
	<%= form.text_field :nazwisko %> </br>
	<%= form.text_area :email %> </br>
	<%= form.submit %>
<% end %>

app/views/clients/index.html.erb
<% @clients.each do |client| %>

<strong> <%= client.imie %> 
<%= client.nazwisko %> </strong>, <%= client.email %> 

<%= link_to "Edit", edit_client_path(client.id), class: 'btn btn-success' %>
<%= link_to 'Show', client_path(client.id),  class: 'btn btn-warning' %>
<%= link_to 'Destroy', client_path(client.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> </p>
<% end %>
<%= link_to "New", new_client_path, class: 'btn btn-primary btn-lg' %>

app/views/clients/new.html.erb
<h1>New Client</h1>

 <%= form_for @client do |form| %>
	<p><strong>Name:</strong> <%= form.text_field :imie %> </p>

	
	<% if @client.errors.any? %>
	
	<ul>
		<% @client.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
			<% end %>
	</ul>
	<% end %>
	
	<p><strong> Surname: </strong> <%= form.text_field :nazwisko %> </p>
	<p> <strong>E-mail:</strong> <%= form.text_field :email %> </p>
	<%= form.submit :submit_client %>
<% end %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p>
  <strong>Imie:</strong>
  <%= @client.imie %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @client.nazwisko %>
</p>

<p>
  <strong>E-mail:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsletter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Newsletter</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="http://localhost:3000/clients">Clients</a></li>
            <li><a href="http://localhost:3000/letters">Messages</a></li>
          </ul>
        </div><!--/.nav-collapse -->
    </nav>

<div class="container" id="newsletter">
		<div class="row">
			<div class="col-md-10">
				<%= yield %>
			</div>
		</div>
</div>

</script>

</body>
</html>

app/views/letters/edit.html.erb
<%= form_for @letter do |form| %>
	<p> <strong> Title: </strong> <%= form.text_field :title %> </p>
	<p> <strong> Topic: </strong> <%= form.text_field :topic %> </p>
	<p> <strong> Content: </strong> <%= form.text_field :content %> </p>
	<%= form.submit %>
<% end %>

app/views/letters/index.html.erb
<% @letters.each do |letter| %>

<p><strong> Title: </strong> <%= letter.title %> </p> 
<p><strong> Topic: </strong> <%= letter.topic %></p>
<p><strong> Content: </strong> <%= letter.content %></p>

<%= link_to "Edit", edit_letter_path(letter.id), class: 'btn btn-success' %>
<%= link_to 'Show', letter_path(letter.id),  class: 'btn btn-warning' %>
<%= link_to 'Destroy', letter_path(letter.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></p>
<% end %>
<%= link_to "New", new_letter_path, class: 'btn btn-primary btn-lg' %>

app/views/letters/new.html.erb
<h1>New letter</h1>

<%= form_for @letter do |form| %>
	<p><strong> Title: </strong> <%= form.text_field :title %> </p>

	
	<% if @letter.errors.any? %>
	
	<ul>
		<% @letter.errors.full_messages.each do |msg| %>
			<li> <%= msg %> </li>
			<% end %>
	</ul>
	<% end %>
	
	<p> <strong> Topic: </strong> <%= form.text_field :topic %> </p>
	<p> <strong> Content: </strong> <%= form.text_field :content %> </p>
	<%= form.submit :submit_letter %>
<% end %>

<%= link_to 'Back', letters_path %>

app/views/letters/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @letter.title %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @letter.topic %>
</p>

<p>
  <strong>Content:</strong>
  <%= @letter.content %>
</p>

<%= link_to 'Edit', edit_letter_path(@letter) %>
<%= link_to 'Back', letters_path %>